### ISSUE TITLE
"FastGettext::TranslationRepository::Mo can work in SAFE mode" fails with Ruby 2.0

### ISSUE THREAD

**Issue by voxik** [grosser/fast_gettext#53]
```
  1) FastGettext::TranslationRepository::Mo can work in SAFE mode
     Failure/Error: `ruby spec/cases/safe_mode_can_handle_locales.rb 2>&1`.should == 'true'
       expected: "true"
            got: "/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:45:in `require': Insecure operation - require (SecurityError)\n\tfrom /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:45:in `require'\n\tfrom /builddir/build/BUILD/rubygem-fast_gettext-0.7.0/usr/share/gems/gems/fast_gettext-0.7.0/lib/fast_gettext/translation_repository.rb:12:in `build'\n\tfrom spec/cases/safe_mode_can_handle_locales.rb:4:in `<main>'\n" (using ==)
       Diff:
       @@ -1,2 +1,5 @@
       -true
       +/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:45:in `require': Insecure operation - require (SecurityError)
       +    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:45:in `require'
       +    from /builddir/build/BUILD/rubygem-fast_gettext-0.7.0/usr/share/gems/gems/fast_gettext-0.7.0/lib/fast_gettext/translation_repository.rb:12:in `build'
       +    from spec/cases/safe_mode_can_handle_locales.rb:4:in `<main>'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/expectations/fail_with.rb:33:in `fail_with'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/matchers/operator_matcher.rb:56:in `fail_with_message'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/matchers/operator_matcher.rb:94:in `__delegate_operator'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/matchers/operator_matcher.rb:84:in `eval_match'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/matchers/operator_matcher.rb:37:in `block in use_custom_matcher_or_delegate'
     # /builddir/build/BUILD/rubygem-fast_gettext-0.7.0/usr/share/gems/gems/fast_gettext-0.7.0/spec/fast_gettext/translation_repository/mo_spec.rb:31:in `block (2 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:111:in `run'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:388:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `map'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:369:in `run'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
     # /usr/share/gems/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `block in autorun'
Finished in 2.2 seconds
168 examples, 1 failure
```

Thank you for looking into this.
